# config.yaml

# Global output directory
data_dir: "data"

# Global GIAB FTP base URL (for VCF, BED, TBI)
giab_base_url: "ftp://ftp-trace.ncbi.nlm.nih.gov/giab/data"

# --- Reference Genomes ---
# Define all reference genomes you might need.
# Each sample will specify which reference_key to use.
references:
  GRCh38:
    url: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
    filename: "GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
  # Example for GRCh37, if needed for older GIAB versions:
  # GRCh37:
  #   url: "ftp://ftp.ncbi.nlm.nih.gov/giab/ftp/technical/reference/GRCh37/human_g1k_v37.fasta.gz" # Example URL, verify
  #   filename: "human_g1k_v37.fasta.gz"

# --- Samples ---
# Define each sample and its associated data URLs and versions.
samples:
  HG001: # NA12878
    id: "NA12878"
    giab_version: "v4.2.1" # Or v3.3.2 for older GRCh37 benchmarks
    reference_build: "GRCh38" # This is for the GIAB path structure and filenames (e.g., HG001_GRCh38_...)
    reference_key: "GRCh38"   # This key points to an entry in the 'references' section above
    fastq_urls:
      # Illumina 300x data from NIST
      - "ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/131219_D00360_005_BH814YADXX/reads/R1.fastq.gz"
      - "ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/131219_D00360_005_BH814YADXX/reads/R2.fastq.gz"

  HG002: # NA24385
    id: "NA24385"
    giab_version: "v4.2.1"
    reference_build: "GRCh38"
    reference_key: "GRCh38"
    fastq_urls:
      # Illumina 2x250bp data from NIST
      - "ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/NIST_HiSeq_HG002_homogeneity-10953946/NHGRI_Illumina_2x250bps/reads/HG002_read1.fastq.gz"
      - "ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/NIST_HiSeq_HG002_homogeneity-10953946/NHGRI_Illumina_2x250bps/reads/HG002_read2.fastq.gz"


# --- Output Path and Filename Templates ---
# These use {wildcards} that Snakemake will fill.
# The filename templates for VCF/BED assume the v4.2.1 naming convention.
# Adjust if using older versions with different naming (e.g. HG001 v3.3.2).

output_ref_dir: "{data_dir}/reference"
output_giab_dir_template: "{data_dir}/giab/{sample_name}/{giab_version}/{reference_build}"
output_fastq_dir_template: "{data_dir}/fastq/{sample_name}"

# Basename for GIAB truth files (VCF, BED). Assumes v4.2.1+ style.
# e.g., HG002_GRCh38_v4.2.1_benchmark
giab_truth_basename_template: "{sample_name}_{reference_build}_{giab_version}_benchmark"

# Filename templates for GIAB truth files
giab_vcf_filename_template: "{giab_truth_basename}.vcf.gz"
giab_tbi_filename_template: "{giab_truth_basename}.vcf.gz.tbi"
giab_bed_filename_template: "{giab_truth_basename}.bed"
