# config.yaml

# Global output directory
data_dir: "data"

# Global GIAB FTP base URL (for VCF, BED, TBI)
giab_base_url: "ftp://ftp-trace.ncbi.nlm.nih.gov/giab/data"

# --- Reference Genomes ---
# Define all reference genomes you might need.
# Each sample will specify which reference_key to use.
# See https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/README_GIAB_Mapping_References.md
references:
  GRCh38:
    url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh38/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz"
    filename: "GRCh38/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz"
  # Example for GRCh37, if needed for older GIAB versions:
  # GRCh37:
  #   url: "ftp://ftp.ncbi.nlm.nih.gov/giab/ftp/technical/reference/GRCh37/human_g1k_v37.fasta.gz" # Example URL, verify
  #   filename: "human_g1k_v37.fasta.gz"

# --- Samples ---
# Define each sample and its associated data URLs and versions.
samples:
  # HG001: # NA12878
  #   id: "NA12878"
  #   giab_version: "v4.2.1"
  #   reference_build: "GRCh38"
  #   reference_key: "GRCh38"
  #   vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/NA12878_HG001/latest/GRCh38/HG001_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
  #   tbi_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/NA12878_HG001/latest/GRCh38/HG001_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi"
  #   bed_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/NA12878_HG001/latest/GRCh38/HG001_GRCh38_1_22_v4.2.1_benchmark.bed"
  #   fastq_urls:
  #     - "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/131219_D00360_005_BH814YADXX/reads/R1.fastq.gz"
  #     - "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/131219_D00360_005_BH814YADXX/reads/R2.fastq.gz"

  HG002: # NA24385
    id: "NA24385"
    giab_version: "v4.2.1"
    reference_build: "GRCh38"
    reference_key: "GRCh38"
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
    tbi_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi"
    bed_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed"
    fastq_urls:
      - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG002.novaseq.pcr-free.35x.R1.fastq.gz"
      - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG002.novaseq.pcr-free.35x.R2.fastq.gz"

  HG003: # NA24149
    id: "NA24149"
    giab_version: "v4.2.1"
    reference_build: "GRCh38"
    reference_key: "GRCh38"
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG003_NA24149_father/latest/GRCh38/HG003_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
    tbi_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG003_NA24149_father/latest/GRCh38/HG003_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi"
    bed_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG003_NA24149_father/latest/GRCh38/HG003_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed"
    fastq_urls:
      - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG003.novaseq.pcr-free.35x.R1.fastq.gz"
      - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG003.novaseq.pcr-free.35x.R2.fastq.gz"

  HG004: # NA24143
    id: "NA24143"
    giab_version: "v4.2.1"
    reference_build: "GRCh38"
    reference_key: "GRCh38"
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG004_NA24143_mother/latest/GRCh38/HG004_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
    tbi_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG004_NA24143_mother/latest/GRCh38/HG004_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi"
    bed_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG004_NA24143_mother/latest/GRCh38/HG004_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed"
    fastq_urls:
      - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG004.novaseq.pcr-free.35x.R1.fastq.gz"
      - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG004.novaseq.pcr-free.35x.R2.fastq.gz"

  # HG005: # NA24631
  #   id: "NA24631"
  #   giab_version: "v4.2.1"
  #   reference_build: "GRCh38"
  #   reference_key: "GRCh38"
  #   vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG005_NA24631_son/latest/GRCh38/HG005_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
  #   tbi_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG005_NA24631_son/latest/GRCh38/HG005_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi"
  #   bed_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG005_NA24631_son/latest/GRCh38/HG005_GRCh38_1_22_v4.2.1_benchmark.bed"
  #   fastq_urls:
  #     - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG005.novaseq.pcr-free.35x.R1.fastq.gz"
  #     - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG005.novaseq.pcr-free.35x.R2.fastq.gz"

  # HG006: # NA24694
  #   id: "NA24694"
  #   giab_version: "v4.2.1"
  #   reference_build: "GRCh38"
  #   reference_key: "GRCh38"
  #   vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG006_NA24694_father/latest/GRCh38/HG006_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
  #   tbi_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG006_NA24694_father/latest/GRCh38/HG006_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi"
  #   bed_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG006_NA24694_father/latest/GRCh38/HG006_GRCh38_1_22_v4.2.1_benchmark.bed"
  #   fastq_urls:
  #     - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG006.novaseq.pcr-free.35x.R1.fastq.gz"
  #     - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG006.novaseq.pcr-free.35x.R2.fastq.gz"

  # HG007: # NA24695
  #   id: "NA24695"
  #   giab_version: "v4.2.1"
  #   reference_build: "GRCh38"
  #   reference_key: "GRCh38"
  #   vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG007_NA24695_mother/latest/GRCh38/HG007_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
  #   tbi_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG007_NA24695_mother/latest/GRCh38/HG007_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi"
  #   bed_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG007_NA24695_mother/latest/GRCh38/HG007_GRCh38_1_22_v4.2.1_benchmark.bed"
  #   fastq_urls:
  #     - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG007.novaseq.pcr-free.35x.R1.fastq.gz"
  #     - "https://opendata.nist.gov/pdrsrv/mds2-2336/input_fastqs/HG007.novaseq.pcr-free.35x.R2.fastq.gz"


# --- Output Path and Filename Templates ---
# These use {wildcards} that Snakemake will fill.
# The filename templates for VCF/BED assume the v4.2.1 naming convention.
# Adjust if using older versions with different naming (e.g. HG001 v3.3.2).

output_ref_dir: "{data_dir}/reference"
output_giab_dir_template: "{data_dir}/giab/{sample_name}/{giab_version}/{reference_build}"
output_fastq_dir_template: "{data_dir}/fastq/{sample_name}"

# Basename for GIAB truth files (VCF, BED). Assumes v4.2.1+ style.
# e.g., HG002_GRCh38_v4.2.1_benchmark
giab_truth_basename_template: "{sample_name}_{reference_build}_{giab_version}_benchmark"

# Filename templates for GIAB truth files
giab_vcf_filename_template: "{giab_truth_basename}.vcf.gz"
giab_tbi_filename_template: "{giab_truth_basename}.vcf.gz.tbi"
giab_bed_filename_template: "{giab_truth_basename}.bed"